In [1]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    print(x)

apple
banana
cherry


In [13]:
q=[1,2,4,45,6]
for i in q:
    if (i<=40):
        print("less than 40 == ",format(i))
    else:
        print("greater ",format(i))
    
    

less than 40 ==  1
less than 40 ==  2
less than 40 ==  4
greater  45
less than 40 ==  6


In [2]:
for x in "banana":
    print(x)

b
a
n
a
n
a


In [6]:
resume = {'name':'mayur','degree':'B.E','specilzation':'Data Scinece'}
for x in resume:
    print(x)

name
degree
specilzation


In [4]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    print(x)
    if x == "banana":
        break

apple
banana


In [6]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    if x == "banana":
        break
    print(x)

apple


In [7]:
def my_function():
    print("Hello from a function")

my_function()

Hello from a function


In [8]:
def my_function(fname):
    print(fname + " Refsnes")

my_function("Emil")
my_function("Tobias")
my_function("Linus")

Emil Refsnes
Tobias Refsnes
Linus Refsnes


In [9]:
x = lambda a : a + 10
print(x(5))

15


In [10]:
x = lambda a, b : a * b
print(x(5, 6))

30


In [11]:
x = lambda a, b, c : a + b + c
print(x(5, 6, 2))

13


In [12]:
cars = ["Ford", "Volvo", "BMW"]
print(cars)

['Ford', 'Volvo', 'BMW']


In [14]:
x = cars[0]
x

'Ford'

In [15]:
cars[0] = "Toyota"
cars

['Toyota', 'Volvo', 'BMW']

In [16]:
x = len(cars)
x

3

In [17]:
class MyClass:
     x = 5
        
print(MyClass)

<class '__main__.MyClass'>


In [18]:
p1 = MyClass()
print(p1.x)

5


In [20]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age)

John
36


In [ ]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age)

In [22]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def myfunc(self):
        print("Hello my name is " + self.name)

p1 = Person("John", 36)
p1.myfunc()


Hello my name is John


In [23]:
class Person:
    def __init__(mysillyobject, name, age):
        mysillyobject.name = name
        mysillyobject.age = age

    def myfunc(abc):
        print("Hello my name is " + abc.name)

p1 = Person("John", 36)
p1.myfunc()

Hello my name is John


In [25]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def myfunc(self):
        print("Hello my name is " + self.name)

p1 = Person("John", 36)

p1.age = 40

print(p1.age)


40


In [26]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def myfunc(self):
        print("Hello my name is " + self.name)

p1 = Person("John", 36)

del p1.age

print(p1.age)


AttributeError: 'Person' object has no attribute 'age'

In [27]:
class Person:
    pass

# having an empty class definition like this, would raise an error without the pass statement


In [28]:
class Person:
    def __init__(self, fname, lname):
        self.firstname = fname
        self.lastname = lname

    def printname(self):
        print(self.firstname, self.lastname)

#Use the Person class to create an object, and then execute the printname method:

x = Person("John", "Doe")
x.printname()

John Doe


In [31]:
class Person:
    def __init__(self, fname, lname):
        self.firstname = fname
        self.lastname = lname


    def printname(self):
        print(self.firstname, self.lastname)

class Student(Person):
    pass

x = Student("Mike", "Olsen")
x.printname()


Mike Olsen


In [32]:
mytuple = ("apple", "banana", "cherry")
myit = iter(mytuple)

print(next(myit))
print(next(myit))
print(next(myit))


apple
banana
cherry


In [33]:
mystr = "banana"
myit = iter(mystr)

print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))


b
a
n
a
n
a


In [34]:
mytuple = ("apple", "banana", "cherry")

for x in mytuple:
    print(x)


apple
banana
cherry


In [35]:
mystr = "banana"

for x in mystr:
    print(x)

b
a
n
a
n
a


In [36]:
def myfunc():
    x = 300
    print(x)

myfunc()


300


In [37]:
def myfunc():
    x = 300
    def myinnerfunc():
        print(x)
    myinnerfunc()

myfunc()


300


In [38]:
x = 300

def myfunc():
    print(x)

myfunc()

print(x)

300
300


In [39]:
x = 300

def myfunc():
    x = 200
    print(x)

myfunc()

print(x)

200
300


In [40]:
def myfunc():
    global x
    x = 300

myfunc()

print(x)

300


In [41]:
x = 300

def myfunc():
    global x
    x = 200

myfunc()

print(x)

200


In [42]:
import datetime

x = datetime.datetime.now()
print(x)

2021-05-21 12:54:40.601440


In [43]:
import datetime

x = datetime.datetime.now()

print(x.year)
print(x.strftime("%A"))


2021
Friday


In [44]:
import datetime

x = datetime.datetime(2020, 5, 17)

print(x)

2020-05-17 00:00:00


In [45]:
import datetime

x = datetime.datetime(2018, 6, 1)

print(x.strftime("%B"))

June


In [46]:
import math

x = math.ceil(1.4)
y = math.floor(1.4)

print(x) # returns 2
print(y) # returns 1


2
1


In [47]:
import math

x = math.pi

print(x)


3.141592653589793


In [48]:
import json

# some JSON:
x =  '{ "name":"John", "age":30, "city":"New York"}'

# parse x:
y = json.loads(x)

# the result is a Python dictionary:
print(y["age"])

30


In [49]:
import json

# a Python object (dict):
x = {
  "name": "John",
  "age": 30,
  "city": "New York"
}

# convert into JSON:
y = json.dumps(x)

# the result is a JSON string:
print(y)

{"name": "John", "age": 30, "city": "New York"}


In [50]:
import re

#Check if the string starts with "The" and ends with "Spain":

txt = "The rain in Spain"
x = re.search("^The.*Spain$", txt)

if x:
  print("YES! We have a match!")
else:
  print("No match")


YES! We have a match!


In [53]:
#The try block will generate a NameError, because x is not defined:

try:
    print(a)
except NameError:
    print("Variable x is not defined")
except:
    print("Something else went wrong")


Variable x is not defined


In [52]:
try:
  print("Hello")
except:
  print("Something went wrong")
else:
  print("Nothing went wrong")


Hello
Nothing went wrong


In [55]:
try:
  print(a)
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")

Something went wrong
The 'try except' is finished


In [60]:
x = -1

if x < 0:
    raise Exception("Sorry, no numbers below zero")


Exception: Sorry, no numbers below zero

In [61]:
username = input("Enter username:")
print("Username is: " + username)


Enter username: my name is mayur
Username is:  my name is mayur


In [62]:
price = 49
txt = "The price is {:.2f} dollars"
print(txt.format(price))


The price is 49.00 dollars


In [63]:
quantity = 3
itemno = 567
price = 49
myorder = "I want {} pieces of item number {} for {:.2f} dollars."
print(myorder.format(quantity, itemno, price))


I want 3 pieces of item number 567 for 49.00 dollars.


In [64]:
age = 36
name = "John"
txt = "His name is {1}. {1} is {0} years old."
print(txt.format(age, name))


His name is John. John is 36 years old.


In [66]:
myorder = "I have a {carname}, it is a {model}."
print(myorder.format(carname = "Ford", model = "Mustang"))


I have a Ford, it is a Mustang.


In [71]:
open("C:/Users/mayur/Desktop.apti preparation.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/mayur/Desktop.apti preparation.txt'

In [74]:
f = open("C:/Users/mayur/Desktop/apti preparation.txt", "r")
print(f.read())


False positive should be low when we are trying to convict a guilty person .An innocent person should never get punished.

Our basic concept of Jurisprudence that the 100 culprits may let go free but no innocent should be punished.


rig and rasso are basically regulization technique or generalization technique,
 this methodlogic is used to  overcome the problem of overfitting ,
it means when we get high accuracy we can say that there is the problem of overfitting and by adding some errrors ,we can reduce the accuracy ,
rig regression in which we penlize the sum of suqare coefficients which is L2 penalti
 and lasso regression which penalizes the sum of absolute values of coefficient iks L1

what is diiference between rig and laso?
lassos we can use for feature selection. both the techniques are used to minimize the multicolinearity.

did analysis on the customer, recipes , man powers also finance

anupamadeshmukh@ymail.com

first name - 'a%' 



In [75]:
f = open("C:/Users/mayur/Desktop/apti preparation.txt", "r")
print(f.readline())

False positive should be low when we are trying to convict a guilty person .An innocent person should never get punished.



In [77]:
f = open("C:/Users/mayur/Desktop/apti preparation.txt", "r")
print(f.readline())
print(f.readline())
print(f.readline())

False positive should be low when we are trying to convict a guilty person .An innocent person should never get punished.



Our basic concept of Jurisprudence that the 100 culprits may let go free but no innocent should be punished.



In [78]:
f = open("C:/Users/mayur/Desktop/apti preparation.txt", "r")
for x in f:
    print(x)


False positive should be low when we are trying to convict a guilty person .An innocent person should never get punished.



Our basic concept of Jurisprudence that the 100 culprits may let go free but no innocent should be punished.





rig and rasso are basically regulization technique or generalization technique,

 this methodlogic is used to  overcome the problem of overfitting ,

it means when we get high accuracy we can say that there is the problem of overfitting and by adding some errrors ,we can reduce the accuracy ,

rig regression in which we penlize the sum of suqare coefficients which is L2 penalti

 and lasso regression which penalizes the sum of absolute values of coefficient iks L1



what is diiference between rig and laso?

lassos we can use for feature selection. both the techniques are used to minimize the multicolinearity.



did analysis on the customer, recipes , man powers also finance



anupamadeshmukh@ymail.com



first name - 'a%' 



In [79]:
f = open("C:/Users/mayur/Desktop/apti preparation.txt", "r")
print(f.readline())
f.close()

False positive should be low when we are trying to convict a guilty person .An innocent person should never get punished.



In [81]:
import numpy as np

In [82]:
arr = np.array([1, 2, 3, 4], ndmin=2)
arr

array([[1, 2, 3, 4]])

In [83]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [84]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])


5th element on 2nd dim:  10


In [85]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [86]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [87]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


[2 3 4 5]


In [88]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [89]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])


[1 2 3 4]


In [90]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [93]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


[2 4]


In [94]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [95]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [96]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])


[3 8]


In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])
arr

[[2 3 4]
 [7 8 9]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [98]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [99]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [100]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [101]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [102]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [103]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [104]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [105]:
!pip install mysql-connector-python

In [106]:
import mysql.connector

In [ ]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="yourusername",
  password="yourpassword"
)

print(mydb)

In [ ]:
def factorial(n):
    if(n==0 or n==1):
        return 1
    else
        return n*factorial(n-1)
      

In [2]:
for i in range(5):
    i=i+1
    
print(i)

5


In [6]:
print(range(0,5))

range(0, 5)


In [2]:
range(1,15)

range(1, 15)

In [10]:
def myfunc():
    a = 200
    print(a)

myfunc()

#print(a)

200


In [12]:
def factorial(n):
    if(n==0 or n==1):
        return 1
    else:
        return n*factorial(n-1)
print
      

In [16]:
import re
s= "tiger is the national animal of India and hockey is the national sport"
pattern = "national"

mo = re.findall(pattern,s)
print(mo)

['national', 'national']


In [15]:
for m in mo:
    print(m.start())

AttributeError: 'str' object has no attribute 'start'

In [1]:
class Solution:
    #Function to reverse a linked list.
    def reverseList(self, head):
        if head is None:
            return None
        
        #taking three pointers to store the current, previous and next nodes.
        prev = None
        current = head
        next = current.next
        
        
        while current is not None:
            #taking the next node as next.
            next = current.next 
            
            #storing the previous node in link part of current node.
            current.next = prev 
            
            #updating prev from previous node to current node.
            prev = current
            
            #updating current node to next node.
            current = next           
        
        return prev


In [3]:
reverseList(1, 2, 3, 4 ,5 ,6)

NameError: name 'reverseList' is not defined

In [5]:
# Definition for singly-linked list.
# class ListNode(object):
#     def __init__(self, x):
#         self.val = x
#         self.next = None

def stringToListNode(input):
    # Generate list from the input
    numbers = json.loads(input)

    # Now convert that list into linked list
    dummyRoot = ListNode(0)
    ptr = dummyRoot
    for number in numbers:
        ptr.next = ListNode(number)
        ptr = ptr.next

    ptr = dummyRoot.next
    return ptr

def prettyPrintLinkedList(node):
    import sys
    while node and node.next:
        sys.stdout.write(str(node.val) + "->")
        node = node.next

    if node:
        print(node.val)
    else:
        print("Empty LinkedList")

def main():
    import sys

    def readlines():
        for line in sys.stdin:
            yield line.strip('\n')

    lines = readlines()
    while True:
        try:
            line = lines.next()
            node = stringToListNode(line)
            prettyPrintLinkedList(node)
        except StopIteration:
            break


if __name__ == '__main__':
    main()

AttributeError: 'generator' object has no attribute 'next'

In [2]:
import math
math.ceil(3.23)

4

In [3]:
import math
math.floor(3.23)

3

In [1]:
# initializing list 
test_list = ['1', '4', '3', '6', '7']
  
# Printing original list
print ("Original list is : " + str(test_list))
  
# using naive method to
# perform conversion
for i in range(0, len(test_list)):
    test_list[i] = int(test_list[i])
      
  
# Printing modified list 
print ("Modified list is : " + str(test_list))

Original list is : ['1', '4', '3', '6', '7']
Modified list is : [1, 4, 3, 6, 7]


### Write a Python Program to print Prime Numbers between 2 numbers?

In [3]:
for num in range(1,10):
    if all(num%i!=0 for i in range(2,num)):
        print(num)

1
2
3
5
7


### Write a Sort function to sort the elements in a list ?

In [4]:
l= [24,55,78,64,25,12,22,11,1,2,44,3,122,23,34]
l.sort(reverse = True)

print(l)

[122, 78, 64, 55, 44, 34, 25, 24, 23, 22, 12, 11, 3, 2, 1]


In [6]:
#without using l.sort function
data_list= [24,55,78,64,25,12,22,11,1,2,44,3,122,23,34]
new_list = []

while data_list:
    minimun = data_list[0] #arbitrary number in list 
    for x in data_list :
        if x > minimun:
            minimun = x
    new_list.append(minimun)
    data_list.remove(minimun)
    
print(new_list)

[122, 78, 64, 55, 44, 34, 25, 24, 23, 22, 12, 11, 3, 2, 1]


### Write a Python program to print Fibonacci Series

In [7]:
def F(n):
    if n == 0: return 0
    elif n ==1 : return 1 
    else: return F(n-1)+F(n-2)
    
for i in range(0,12):
    print(F(i))
    

0
1
1
2
3
5
8
13
21
34
55
89


### Write a Python program to print a list in reverse?

In [9]:
li = [21,1,3,4,5,6,7,8,9,19,34,36,48,50,51]

def rev(l):
    return l[::-1]
    
rev(li)

[51, 50, 48, 36, 34, 19, 9, 8, 7, 6, 5, 4, 3, 1, 21]

### Write a Python program to check whether a string is a Palindrome or not ?

In [2]:
def isPalindrome(s):
    #use predefined function to 
    #reverse to string print(s)
    rev = "".join(reversed(s))
    
    # checking if both string are 
    #equal or not
    
    if (s==rev):
        return True
    return False
isPalindrome("madam")

    
    
    
    

True

### Write a Python program to print set of duplicates in a list?

In [15]:
l = [1,2,3,4,4,5,5,6,1]
print(set([x for x in l if l.count(x) > 1]))

{1, 4, 5}


### Write a Python program to print number of words in a given sentence ?

In [16]:
s =  "I am having a very nice day"
print(len(s.split()))

7


### Given an array arr[] of n elements, write a Python function to search a given element x in arr[].?

In [18]:
def search(arr,x):
    
    for i in range(len(arr)):
        
        if arr[i] == x:
            return i 
    print("Not present in the list")
    
    
l = [1,2,3,4,4,5,5,6,1]

search(l,4)  
    

3

### Write a Python program to implement a Binary Search ?

In [22]:
def binary_search(array, target):
    lower = 0
    upper = len(array)
    while lower < upper: #use < instead of <=
        x = lower + (upper -lower) // 2
        val = array[x]
        if target == val:
            return x
        elif target > val:
            if lower == x:
                break
            lower = x
        elif target < val:
            upper = x
            
binary_search(l,5)

6

### Write a Python program to plot a simple bar chart ?

In [4]:
class computer:
    def __init__(self):
        print("in init")
    
    def config(self):
        print("i5",'8gb','asus')
        
comp = computer()

comp.config()

in init
i5 8gb asus


In [6]:
class computer:
    def __init__(self,cpu,ram):
        self.cpu = cpu
        self.ram = ram
        
    
    def config(self):
        print("Config is ",self.cpu,self.ram)
        
comp1 = computer('i5','8gb')
comp2 = computer('i3','4gb')

comp1.config()
comp2.config()

Config is  i5 8gb
Config is  i3 4gb


In [12]:
class student:
    school = "mvk"
    def __init__(self,m1,m2,m3):
        self.m1 = m1
        self.m2 = m2 
        self.m3 = m3
        
    def avg(self):
        return (self.m1+self.m2+self.m3)/3
    
s1  = student(34,67,32)
s2 = student(89,32,12)

print(s1.avg())

44.333333333333336


In [13]:
class student:
    school = "mvk"
    def __init__(self,m1,m2,m3):
        self.m1 = m1
        self.m2 = m2 
        self.m3 = m3
        
    def avg(self):
        return (self.m1+self.m2+self.m3)/3
    
    @classmethod
    def info(cls):
        return cls.school
    
s1  = student(34,67,32)
s2 = student(89,32,12)

print(s1.avg())
print(student.info())

44.333333333333336
mvk


#### instance variable class method works with class variable and static works with nothing , it has , if you want to do something extra with your class nothing to do with class variables or instance variables go with static

# class :
    variable 
    method/Function

In [19]:
###############################################

# class inside a class


class :
    class:

In [15]:
class student:
    def __init__(self,name,rollno):
        self.name = name
        self.rollno = rollno
        self.lap = self.Laptop()
        
    def show(self):
        print(self.name,self.rollno)
        
    class Laptop:
        def __init__(self):
            self.brand = 'HP'
            self.cpu = 'i5'
            self.ram = 0
            
            
s1 = student('Navin',2)
s2 = student('Jenny',3)
        
    
s1.show()

lap1 = s1.lap
lap2 = s2.lap
    
    

Navin 2


In [18]:
class student:
    def __init__(self,name,rollno):
        self.name = name
        self.rollno = rollno
        self.lap = self.Laptop()
        
    def show(self):
        print(self.name,self.rollno)
        self.lap.show()
        
    class Laptop:
        def __init__(self):
            self.brand = 'HP'
            self.cpu = 'i5'
            self.ram = 8
            
        def show(self):
            print(self.brand, self.cpu, self.ram)
            
            
s1 = student('Navin',2)
s2 = student('Jenny',3)
        
    
s1.show()

#lap1 = s1.Laptop()
#lap2 = s2.Laptop()

Navin 2
HP i5 8


# inheritance

In [20]:
def find_sum(n):
    if n==1:
        return 1
    return n + find_sum(n-1)

def fib(n):
    # 0,1,1,2,3,5,8 <-- fibonacci numbers
    # --------------
    # 0,1,2,3,4,5,6 <-- index
    if n==0 or n==1:
        return n
    return fib(n-1) + fib(n-2)

if __name__=='__main__':
    print(find_sum(5))
    print(fib(10))

15
55


In [2]:
nameList = ['Harsh', 'Pratik', 'Bob', 'Dhruv']
print( nameList[1][-1])

k
